apiVersion: v1
kind: Service
metadata:
  name: oms-admin-portal
  namespace: oms-admin-portal

  labels:
    name: oms-admin-portal
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080
    - name: tcp
      port: 15071
      targetPort: 15071
    - name: file-upload
      port: 8081
      targetPort: 8081
  selector:
    app: oms-admin-portal


