apiVersion: v1
kind: Service
metadata:
  labels:
    name: early-access
  name: ea
  namespace: early-access
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 1323
  selector:
    app: early-access
  type: ClusterIP
