---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-pusher
  namespace: email-pusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-pusher
  template:
    metadata:
      labels:
        app: email-pusher
    spec:
      volumes:
         - name: service-account
           secret:
             secretName: bucket-service-account
      containers:
        - name: envoy
          image: gcr.io/stock-x-342909/envoy:email-pusher-$IMAGE_TAG
          env:
            - name: DEV_MODE
              value: "false"

          ports:
            - containerPort: 8080


        - name: email-pusher
          image: gcr.io/stock-x-342909/email-pusher:$IMAGE_TAG
          volumeMounts:
            - mountPath: /etc/stockx
              name: service-account

          env:
            - name: DEV_MODE
              value: "false"
            - name: "EMAIL_PUSHER_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "EMAIL_PUSHER_CONSUL_PATH"
              value: "email-pusher"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/etc/stockx/stockx-service-account.json"

          ports:
            - containerPort: 15070
