FROM envoyproxy/envoy-dev:3b45d6cf465b8ce3c268edaa5c70722811dbb39f

RUN apt-get update \
    && apt-get install --no-install-recommends -y curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

COPY integration/etc/envoy/envoy.landing-page.yaml /etc/envoy/envoy.yaml

RUN chmod go+r /etc/envoy/envoy.yaml
