---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nblsl-web
  namespace: nblsl-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nblsl-web
  template:
    metadata:
      labels:
        app: nblsl-web
    spec:
      # volumes:
      #   - name: envoy-config
      #     configMap:
      #       name: envoy-config
      #   - name: tls-cert
      #     secret:
      #       secretName: tls-cert
      containers:
        #- name: envoy
        #image: gcr.io/stock-x-342909/envoy-nblsl-web:0.0.3
        # volumeMounts:
        #   - mountPath: "/etc/cert"
        #     name: tls-cert
        #   - mountPath: "/etc/envoy/"
        #     name: envoy-config

        # env:
        #   - name: DEV_MODE
        #     value: "false"

        # ports:
        #   - containerPort: 8080

        - name: nblsl-web
          image: gcr.io/stock-x-342909/nblsl-web:$IMAGE_TAG
          env:
            - name: DEV_MODE
              value: "false"
            - name: NODE_OPTIONS
              value: "--openssl-legacy-provider"

          ports:
            - containerPort: 3000
