apiVersion: v1
kind: Service
metadata:
  name: nblsl-web
  namespace: nblsl-web
  labels:
    name: nblsl-web
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443

  selector:
    app: nblsl-web