apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: centrifugo

  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  labels:
    name: proxy
spec:
  type: ClusterIP
  ports:
    - name: web1
      port: 80
      targetPort: 8081

  selector:
    app: proxy
