apiVersion: v1
kind: Service
metadata:
  name: ea
  namespace: early-access

  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  labels:
    name: early-access
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 1323

  selector:
    app: early-access
