---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-scheduler
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-scheduler
  template:
    metadata:
      labels:
        app: portfolio-scheduler
    spec:
      containers:
        - name: portfolio-scheduler
          image: gcr.io/stock-x-342909/portfolio:$IMAGE_TAG
          #          resources:
          #            requests:
          #              memory: "64Mi"
          #              cpu: "50m"
          #            limits:
          #              memory: "128Mi"
          #              cpu: "500m"
          env:
            - name: DEV_MODE
              value: "false"
            - name: "PORTFOLIO_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "PORTFOLIO_CONSUL_PATH"
              value: "portfolio"

          ports:
            - containerPort: 15070
          args: [ "chart_data_schedule" ]

