apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-rejected-reason-scheduler
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-rejected-reason-scheduler
  template:
    metadata:
      labels:
        app: order-rejected-reason-scheduler
    spec:
      containers:
        - name: order-rejected-reason-scheduler
          image: gcr.io/stock-x-342909/portfolio:b49eecf
          env:
            - name: DEV_MODE
              value: "false"
            - name: "PORTFOLIO_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "PORTFOLIO_CONSUL_PATH"
              value: "portfolio"

          ports:
            - containerPort: 15070
          args: [ "rejected_reason_tracker" ]