apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: portfolio

  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  labels:
    name: portfolio
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080
    - name: tcp
      port: 15070
      targetPort: 15070
    - name: envoy-metrics  #only in prod
      port: 9901
      protocol: TCP
      targetPort: 9901
    - name: prom   #only in prod
      port: 9092
      protocol: TCP
      targetPort: 9092

  selector:
    app: portfolio
