---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trigger-order-scheduler
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trigger-order-scheduler
  template:
    metadata:
      labels:
        app: trigger-order-scheduler
    spec:
      containers:
        - name: trigger-order-scheduler
          image: gcr.io/stock-x-342909/portfolio:$IMAGE_TAG
          env:
            - name: DEV_MODE
              value: "false"
            - name: "PORTFOLIO_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "PORTFOLIO_CONSUL_PATH"
              value: "portfolio"

          ports:
            - containerPort: 15070
          args: [ "schedule_trigger_order" ]

