---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-order-tracker-listener
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-order-tracker-listener
  template:
    metadata:
      labels:
        app: user-order-tracker-listener
    spec:
      containers:
        - name: user-order-tracker-listener
          image: gcr.io/stock-x-342909/portfolio:$IMAGE_TAG
          env:
            - name: DEV_MODE
              value: "false"
            - name: "PORTFOLIO_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "PORTFOLIO_CONSUL_PATH"
              value: "portfolio"

          ports:
            - containerPort: 15070
          args: [ "user_order_tracker_listen" ]

