---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-info-listener
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta-info-listener
  template:
    metadata:
      labels:
        app: meta-info-listener
    spec:
      volumes:
        - name: service-account
          secret:
            secretName: bucket-service-account
      containers:
        - name: meta-info-listener
          image: gcr.io/stock-x-342909/auth:$IMAGE_TAG
          volumeMounts:
            - mountPath: /etc/stockx
              name: service-account

          env:
            - name: DEV_MODE
              value: "false"
            - name: "AUTH_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "AUTH_CONSUL_PATH"
              value: "auth"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/etc/stockx/stockx-service-account.json"

          ports:
            - containerPort: 15071

          args: [ "meta_info_listen" ]
