apiVersion: v1
kind: Service
metadata:
  name: trek-landing
  namespace: trek-landing
  labels:
    name: trek-landing
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443

  selector:
    app: trek-landing