apiVersion: v1
kind: Service
metadata:
  name: pubsub
  namespace: pubsub

  labels:
    app: pubsub
spec:
  type: LoadBalancer
  ports:
    - name: tcp
      port: 9092
      targetPort: 9092
  selector:
    app: pubsub
