---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-info
  namespace: bank-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-info
  template:
    metadata:
      labels:
        app: bank-info
    spec:
      containers:
        - name: envoy
          image: gcr.io/stock-x-342909/envoy:bank-info-$IMAGE_TAG
          env:
            - name: DEV_MODE
              value: "false"

          ports:
            - containerPort: 8080

        - name: bank-info
          args:
            - serve
          image: gcr.io/stock-x-342909/bank-info:$IMAGE_TAG
          #          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "50m"
#            limits:
#              memory: "128Mi"
#              cpu: "500m"
          env:
            - name: DEV_MODE
              value: "false"
            - name: "BANK_INFO_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "BANK_INFO_CONSUL_PATH"
              value: "bank-info"

          ports:
            - containerPort: 15071
