apiVersion: v1
kind: Service
metadata:
  name: tyrion
  namespace: tyrion

  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  labels:
    name: tyrion
spec:
  type: ClusterIP
  ports:
    - name: tyrion
      port: 80
      targetPort: 8080
    - name: tcp
      port: 15072
      targetPort: 15072
    - name: envoy-metrics  #only in prod
      port: 9901
      protocol: TCP
      targetPort: 9901
    - name: prom   #only in prod
      port: 9092
      protocol: TCP
      targetPort: 9092

  selector:
    app: tyrion
