apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: admin-portal-local
  labels:
    name: admin-portal
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/"
    prometheus.io/port: "9092"
    prometheus.io/scheme: "http"

spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 8080
    - name: prom
      port: 9092
      targetPort: 9092
    - name: tcp
      port: 15072
      targetPort: 15072
  selector:
    app: admin-portal
