---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varys
  namespace: varys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varys
  template:
    metadata:
      labels:
        app: varys
    spec:
      volumes:
        - name: gcp
          secret:
            secretName: bucket-service-account
      containers:
        - name: envoy
          image: gcr.io/stock-x-342909/envoy:varys-$IMAGE_TAG
          env:
            - name: DEV_MODE
              value: "false"

          ports:
            - containerPort: 8080


        - name: varys
          image: gcr.io/stock-x-342909/varys:$IMAGE_TAG
          volumeMounts:
            - name: gcp
              mountPath: /etc/gcp
          env:
            - name: DEV_MODE
              value: "false"
            - name: "VARYS_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "VARYS_CONSUL_PATH"
              value: "varys"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/etc/gcp/stockx-service-account.json"

          ports:
            - containerPort: 15070
          args: [ "serve" ]
