apiVersion: v1
kind: Service
metadata:
  name: me
  namespace: me

  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  labels:
    name: me
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080
    - name: tcp
      port: 15072
      targetPort: 15072
    - name: file-upload
      port: 8081
      targetPort: 8081
    - name: envoy-metrics  #only in prod
      port: 9901
      protocol: TCP
      targetPort: 9901
    - name: prom   #only in prod
      port: 9092
      protocol: TCP
      targetPort: 9092

  selector:
    app: me


