apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: metrics
  namespace: me

spec:
  endpoints:
    - path: /stats/prometheus
      port: envoy-metrics
    - path: /metrics
      port: prom
  namespaceSelector:
    matchNames:
      - me
  selector:
    matchLabels:
      name: me