apiVersion: v1
kind: Service
metadata:
  name: swagger
  namespace: swagger

  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  labels:
    name: swagger
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 8080

  selector:
    app: swagger
