---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zag-webhook
  namespace: zag-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zag-webhook
  template:
    metadata:
      labels:
        app: zag-webhook
    spec:
      # volumes:
      #   - name: service-account
      #     secret:
      #       secretName: bucket-service-account
      containers:
        - name: zag-webhook
          image: gcr.io/stock-x-342909/zag-webhook:$IMAGE_TAG

          env:
            - name: DEV_MODE
              value: "false"
            - name: "ZAG_WEBHOOK_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "ZAG_WEBHOOK_CONSUL_PATH"
              value: "zag-webhook"

          ports:
            - containerPort: 15070