apiVersion: v1
kind: Service
metadata:
  name: zag-webhook
  namespace: zag-webhook

  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  labels:
    name: zag-webhook
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 15070
    - name: envoy-metrics  #only in prod
      port: 9901
      protocol: TCP
      targetPort: 9901
    - name: prom   #only in prod
      port: 9092
      protocol: TCP
      targetPort: 9092

  selector:
    app: zag-webhook
