---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest
  namespace: guest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guest
  template:
    metadata:
      labels:
        app: guest
    spec:
      containers:
        - name: envoy
          image: gcr.io/stock-x-342909/envoy:guest-0.0.3b
          env:
            - name: DEV_MODE
              value: "false"

          ports:
            - containerPort: 8080

        - name: guest
          image: gcr.io/stock-x-342909/guest:0.0.1-rc3
          #          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "50m"
#            limits:
#              memory: "128Mi"
#              cpu: "500m"
          env:
            - name: DEV_MODE
              value: "false"
            - name: "GUEST_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "GUEST_CONSUL_PATH"
              value: "guest"

          ports:
            - containerPort: 15071
