---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-parser
  namespace: feed-parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-parser
  template:
    metadata:
      labels:
        app: feed-parser
    spec:
      volumes:
         - name: service-account
           secret:
             secretName: bucket-service-account
      containers:
#        - name: envoy
#          image: gcr.io/stock-x-342909/envoy:feed-parser-$IMAGE_TAG
#          env:
#            - name: DEV_MODE
#              value: "false"
#
#          ports:
#            - containerPort: 8080


        - name: feed-parser
          image: gcr.io/stock-x-342909/feed-parser:$IMAGE_TAG
          volumeMounts:
            - mountPath: /etc/stockx
              name: service-account

          env:
            - name: DEV_MODE
              value: "false"
            - name: "FEED_PARSER_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "FEED_PARSER_CONSUL_PATH"
              value: "feed-parser"

          ports:
            - containerPort: 15076
