---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-scheduler
  namespace: feed-parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator-scheduler
  template:
    metadata:
      labels:
        app: simulator-scheduler
    spec:
      containers:
        - name: feed-parser-simulator-scheduler
          image: gcr.io/stock-x-342909/feed-parser:$IMAGE_TAG
          env:
            - name: DEV_MODE
              value: "false"
            - name: "FEED_PARSER_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "FEED_PARSER_CONSUL_PATH"
              value: "feed-parser"

          ports:
            - containerPort: 15076
          args: [ "schedule_simulator" ]

