apiVersion: v1
kind: Service
metadata:
  name: landing-page
  namespace: landing-page
  labels:
    name: landing-page
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 8443

  selector:
    app: landing-page
