---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deposit-listener
  namespace: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deposit-listener
  template:
    metadata:
      labels:
        app: deposit-listener
    spec:
      volumes:
        - name: service-account
          secret:
            secretName: bucket-service-account

      containers:
        - name: deposit-listener
          image: gcr.io/stock-x-342909/bank:$IMAGE_TAG
          volumeMounts:
            - mountPath: /etc/stockx
              name: service-account

          env:
            - name: DEV_MODE
              value: "false"
            - name: "BANK_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "BANK_CONSUL_PATH"
              value: "bank"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/etc/stockx/stockx-service-account.json"

          ports:
            - containerPort: 15072
          args: [ "deposit_listen" ]

