---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
  namespace: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:

      # volumes:
      #   - name: envoy-config
      #     configMap:
      #       name: envoy-config
      #   - name: tls-cert
      #     secret:
      #       secretName: tls-cert
      volumes:
        - name: service-account
          secret:
            secretName: bucket-service-account
      containers:
        - name: envoy
          image: gcr.io/stock-x-342909/envoy:bank-$IMAGE_TAG
          env:
            - name: DEV_MODE
              value: "false"

          ports:
            - containerPort: 8080

        - name: bank
          image: gcr.io/stock-x-342909/bank:$IMAGE_TAG
          volumeMounts:
            - mountPath: /etc/stockx
              name: service-account
          #          resources:
          #            requests:
          #              memory: "64Mi"
          #              cpu: "50m"
          #            limits:
          #              memory: "128Mi"
          #              cpu: "500m"
          env:
            - name: DEV_MODE
              value: "false"
            - name: "BANK_CONSUL_URL"
              value: "consul-server.consul:8500"
            - name: "BANK_CONSUL_PATH"
              value: "bank"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/etc/stockx/stockx-service-account.json"

          ports:
            - containerPort: 15072
          args: [ "serve" ]

